version: 2.1

orbs:
  gas-library:
    commands:
      prepare-node-command:
        steps:
          - run: |
              apk add --no-cache nodejs

      make-command:
        parameters:
          target:
            type: "string"
        steps:
          - run: |
              make <<parameters.target>>

      upload-release-artifacts-command:
        parameters:
          version:
            type: "string"
        steps:
          - attach_workspace:
              at: ./artifacts
          - run:
              name: "Publish Release on GitHub"
              command: |
                go get github.com/tcnksm/ghr
                ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete <<parameters.version>> ./artifacts/
    executors:
      architect:
        docker:
          - entrypoint: /bin/bash
            image: quay.io/giantswarm/architect:latest

workflows:
  version: 2

  build_and_check:
    jobs:
      - gas-library/prepare-node-command:
          context: architect
      - gas-library/make-command:
        context: architect
        target: test
        steps:
        - store_artifacts:
            path: ./lib-output

  deploy:
    jobs:
      - gas-library/upload-release-artifacts-command:
        context: architect
