name: JS Dependency Audit

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/npm-shrinkwrap.json'
      - '**/yarn.lock'
      - '**/.yarnrc'
      - '**/.yarnrc.yml'
      - '**/pnpm-lock.yaml'
      - '**/pnpm-workspace.yaml'

permissions: {}

jobs:
  audit:
    uses: giantswarm/github-workflows/.github/workflows/js-dependency-audit.yaml@5c3d73b402c47d6768fc1e8a4aa56f27d79bf580 # main
    permissions:
      contents: read
      pull-requests: write
