name: Upload Release Artifacts
on:
  release:
    types: [published]
jobs:
  upload_release_files:
    name: Upload Release Files
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Build Library
        run: make lib
      - name: Upload Files to Release
        env:
          GITHUB_TOKEN: "${{ secrets.TAYLORBOT_GITHUB_ACTION }}"
          VERSION: "${{ github.event.release.name }}"
        run: |
          RELEASE="$(gh release list | grep "$VERSION")"
          gh release view --json assets "$VERSION" | jq '.assets[].name' | xargs gh release delete-asset -y "$VERSION"
          gh release upload --clobber "$VERSION" lib-output/*
