name: Upload Release Artifacts
on:
  release:
jobs:
  upload_release_files:
    name: Upload Release Files
    runs-on: ubuntu-20.04
    env:
      VERSION: ${{ github.event.release.name }}
      COMMITISH: ${{ github.event.release.target_commitish }}
      SENDER: ${{ github.event.release.sender }}
      REPOSITORY: ${{ github.event.release.repository }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Build Library
        run: make lib
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '=1.18.1'
      - name: Upload Files to Release
        env:
          GITHUB_TOKEN: "${{ secrets.TAYLORBOT_GITHUB_ACTION }}"
        run: |
          go install github.com/tcnksm/ghr@v0.16.0
          ghr -t ${GITHUB_TOKEN} -u ${SENDER} -r ${REPOSITORY} -c ${COMMITISH} -delete ${VERSION} ./lib-output/
